projects:
  app:
    schemaPath: src/schema/index.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma/datamodel.graphql
    extensions:
      prisma: prisma/prisma.yml
