version: '3'
services:
  bm_prisma:
    depends_on:
      - bm_mysql
    image: prismagraphql/prisma:1.17
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: bm_mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
            rawAccess: true
  bm_mysql:
    image: mysql:5.7
    logging:
      driver: none
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  bm:
    build: .
    depends_on:
      - bm_mysql
      - bm_prisma
    ports:
      - "2222:22"
      - "4000:4000"
    volumes:
      - "~/.bit-docker:/scopes"
      - "~/.bit-access-keys:/home/bit/.ssh"
      - ".:/home/bit/server"
volumes:
  mysql:
